config/routes.rb
Rails.application.routes.draw do
  resources :sales_uploads, only:[:index, :show, :new, :create]
  resources :sales_uploads do
    member do
      get 'error_file'
    end
  end
  root "sales_uploads#new"

end

app/models/sale.rb
# == Schema Information
#
# Table name: sales
#
#  id              :integer          not null, primary key
#  sales_upload_id :integer
#  customer        :string           not null
#  description     :string           not null
#  price           :decimal(18, 2)   not null
#  quantity        :integer          not null
#  address         :string           not null
#  supplier        :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Sale < ActiveRecord::Base
  belongs_to :sales_upload

  def total
    price * quantity
  end
end

app/models/sales_upload.rb
# == Schema Information
#
# Table name: sales_uploads
#
#  id          :integer          not null, primary key
#  name        :string
#  description :string
#  status      :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class SalesUpload < ActiveRecord::Base
  has_many :sales
  enum status:[:processing, :ok, :processed_with_errors, :unprocessable]

  def total
    #Warning this is subjected to N+1 queries, need to be replaced with SUM SQL
    sales.inject(BigDecimal.new(0)){|acc, sale| acc + sale.total}
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sales_uploads_controller.rb
class SalesUploadsController < ApplicationController
  respond_to :html

  # GET /sales_uploads
  def index
    @sales_uploads = SalesUploadDecorator.decorate_collection(SalesUpload.last(15)) #TODO Pagination
  end

  # GET /sales_uploads/1
  def show
    @sales_upload = SalesUpload.find(params[:id]).decorate
  end

  # GET /sales_uploads/new
  def new
    @sales_upload = SalesUploadForm.new(SalesUpload.new)
  end

  # POST /sales_uploads
  def create
    @sales_upload = SalesUploadForm.new(SalesUpload.new)

    if @sales_upload.validate(sales_upload_params)
      @sales_upload.save
      FileParser.new(@sales_upload).call
      redirect_to @sales_upload, @sales_upload.model.decorate.message
    else
      render :new
    end
  end

  def error_file
    sales_upload = SalesUpload.find(params[:id])
    file_path = File.join(Rails.root, 'tmp', "erro_#{sales_upload.id}.txt")
    if sales_upload.processed_with_errors? && File.file?(file_path)
      send_file file_path, type: 'text/plain'
    else
      render "404.html"
    end
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def sales_upload_params
    params.require(:sales_upload).permit(:name, :description, :file)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sales_uploads_helper.rb
module SalesUploadsHelper
end

app/views/layouts/application.slim
doctype html
html lang="en"
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport" /
    meta name="robots" content="all,index,nofollow"
    title Nexaas Challenge
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  body
    nav.navbar.navbar-inverse.bg-primary.navbar-toggleable-md
      button.navbar-toggler.navbar-toggler-right aria-controls="adminNavbar" aria-expanded="false" aria-label=("Toggle navigation") data-target="#adminNavbar" data-toggle="collapse" type="button"
        span.navbar-toggler-icon
      a.navbar-brand href='/' Nexaas Challenge

    .container
      br
      - flash.each do |key, value|
        .alert.alert-dismissible.fade.show role='alert' class="#{key == 'alert' ? 'alert-danger' : 'alert-success'}"
          button.close aria-label="close" data-dismiss="alert" data-close="" type="button"
            span aria-hidden="true" &times;
          h5= value
      = yield

app/views/sales_uploads/_form.html.slim
= simple_form_for(@sales_upload) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :description
    = f.input :file, as: :file

  .form-actions
    = f.button :submit, "Enviar"
    = link_to 'Voltar', sales_uploads_path, class:'btn'

app/views/sales_uploads/index.html.slim
.row
  p#notice= notice
  h1 Arquivos Enviados
  .table-responsive
    table.table.table-striped
      thead
        tr
          th Data
          th Nome
          th Descrição
          th Status
          th Total
          th
          th

      tbody
        - @sales_uploads.each do |sales_upload|
          tr
            td = sales_upload.formatted_datetime
            td = sales_upload.name
            td = sales_upload.description
            td = sales_upload.formatted_status
            td = sales_upload.formatted_total
            td = link_to 'Show', sales_upload
            td = link_to('download erros', error_file_sales_upload_path(sales_upload)) if sales_upload.processed_with_errors?

  br
  = link_to 'Subir Novo Arquivo', new_sales_upload_path, class:'btn btn-primary'

app/views/sales_uploads/new.html.slim
h1 New sales_upload

== render 'form'

app/views/sales_uploads/show.html.slim
.row
  p#notice= notice
  h1 Detalhes de Arquivo
  hr
  ul
    li
      strong Data:&nbsp;
      = @sales_upload.formatted_datetime
    li
      strong Nome:&nbsp;
      = @sales_upload.name
    li
      strong Descrição:&nbsp;
      = @sales_upload.description
    li
      strong Status:&nbsp;
      = @sales_upload.formatted_status

  .table-responsive
    table.table.table-striped
      thead
        tr
          th Consumidor
          th Descrição
          th Preço Unitário
          th Quantidade
          th Endereço
          th Fornecedor
          th Total
      tbody
        -@sales_upload.decorated_sales.each do |sale|
          tr
            td= sale.customer
            td= sale.description
            td= sale.price
            td= sale.quantity
            td= sale.address
            td= sale.supplier
            td= sale.formatted_total
      tfooter
        tr
          th colspan=6 Total
          th= @sales_upload.formatted_total
    = link_to 'Voltar', sales_uploads_path, class:'btn'